# Generated by Django 6.1.1 on 2026-09-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_customer_sale_saleitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_code",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
