# Generated by Django 6.1.1 on 2026-09-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_product_product_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
