# Generated by Django 6.1.1 on 2026-09-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_salereturn_salereturnitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
