# Generated by Django 6.1.1 on 2026-09-28 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_sale_is_confirmed"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_number", models.CharField(blank=True, max_length=100)),
                ("bill_date", models.DateField(blank=True, null=True)),
                (
                    "bill_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="purchase_drafts/"
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_drafts",
                        to="core.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseDraftItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_product_code", models.CharField(blank=True, max_length=100)),
                ("original_product_name", models.CharField(blank=True, max_length=200)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_identified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.purchasedraft",
                    ),
                ),
                (
                    "matched_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_draft_items",
                        to="core.product",
                    ),
                ),
            ],
        ),
    ]
