# Generated by Django 6.1.1 on 2026-09-28 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_purchasedraft_purchasedraftitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasedraft",
            name="original_supplier_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="purchasedraft",
            name="bill_image",
            field=models.FileField(blank=True, null=True, upload_to="purchase_drafts/"),
        ),
        migrations.AlterField(
            model_name="purchasedraft",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_drafts",
                to="core.supplier",
            ),
        ),
    ]
