# Generated by Django 6.1.1 on 2026-09-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_purchasedraft_original_supplier_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="bill_image",
            field=models.FileField(blank=True, null=True, upload_to="bills/"),
        ),
    ]
