# Generated by Django 6.1.1 on 2026-09-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_purchase_bill_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasedraftitem",
            name="selling_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
