# Generated by Django 6.1.1 on 2026-10-06 19:29

from django.db import migrations, models


def seed_categories(apps, schema_editor):
    Category = apps.get_model("core", "Category")
    Product = apps.get_model("core", "Product")

    descriptions = {
        "Tiles": "Floor and wall tiles",
        "Granite": "Granite slabs and products",
        "Marble": "Marble slabs and products",
        "Adhesive": "Tile fixing adhesive",
        "Grout": "Tile joint filling grout",
    }

    for name, description in descriptions.items():
        Category.objects.get_or_create(
            name=name,
            defaults={
                "description": description,
                "status": "Inactive" if name == "Grout" else "Active",
            },
        )

    for name in (
        Product.objects
        .exclude(category="")
        .values_list("category", flat=True)
        .distinct()
    ):
        Category.objects.get_or_create(
            name=name,
            defaults={"description": "", "status": "Active"},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_purchasedraftitem_selling_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="supplier",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="supplier",
            name="contact_person",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="supplier",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="supplier",
            name="gstin",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="supplier",
            name="outstanding",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="supplier",
            name="pincode",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="supplier",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="supplier",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Active",
                max_length=20,
            ),
        ),
        migrations.RunPython(seed_categories, migrations.RunPython.noop),
    ]
