# Generated by Django 6.1.1 on 2026-10-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_category_supplier_city_supplier_contact_person_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="purchasedraftitem",
            name="size",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="purchasedraftitem",
            name="weight",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
