# Generated by Django 6.1.1 on 2026-10-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_product_size_weight_and_draft_ocr_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasedraft",
            name="supplier_gstin",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="purchasedraft",
            name="supplier_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
