# Generated by Django 6.1.1 on 2026-10-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_adminphonechallenge_adminprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleitem",
            name="purchase_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
