# Generated by Django 6.1.1 on 2026-10-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_saleitem_purchase_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasedraft",
            name="supplier_address",
            field=models.TextField(blank=True),
        ),
    ]
