# Generated by Django 6.1.1 on 2026-10-06 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_purchasedraft_supplier_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchasedraft",
            name="supplier_address",
        ),
    ]
